branch-defaults:
  master:
    environment: udagram-dev-dev
environment-defaults:
  udagram-dev-dev:
    branch: null
    repository: null
global:
  application_name: udagram-dev
  default_ec2_keyname: udagram
  default_platform: Node.js 12 running on 64bit Amazon Linux 1
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
